feat: add homework 1
timkotov2003/myrepository pull request #1
Opened 2023-10-14 08:13 UTC by timkotov2003

2023-10-15 09:25 UTC, SHvatov requested changes
@timkotov2003 оставил пару комментариев, посмотри их, пожалуйста.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +    public static final int SECONDS = 60;
Название стоит конкретизировать, не понятно, о каких секундах идет речь. SECONDS_UPPER_LIMIT или SECONDS_IN_MINUTE

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +        int minuts;
Слишком раннее объявление переменных. Их лучше объявлять как можно ближе к инициализации, а в идеале — совмещать.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +            minuts = Integer.parseInt(input.split(":")[0]);
Советую почитать вот эту статью - https://www.baeldung.com/java-exceptions-performance. Создание и перехват исключений штука относительно дорогостоящая, поэтому их стоит использовать в исключительных ситуациях (прошу прощения за каламбур). В данном случае заранее известен формат входной строки, поэтому ее можно самостоятельно провалидировать и вернуть -1, если она невалидная. Это можно сделать, к примеру, через регулярки.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +        if (seconds >= SECONDS) {
`-01:-01` в текущей реализации выдаст -61 :)

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task3.java
> +        int minElementFirstArray = Integer.MAX_VALUE;
Поиск минимального/максимального значений стоит вынести в метод, чтобы не дублировать код.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task5.java
> +        String s = Integer.toString(Math.abs(num));
Наименование переменным стоит давать более детальные, чтобы можно было понять, за что она отвечает и для чего нужна.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        if (Math.abs(num) == KAPREKAR_CONST) {
Не хватает валидации входных данных и соответствующих тестов. К примеру, при `num == 1234567` в тестах я ловлю `java.lang.StackOverflowError`.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        minNumInString = String.format("%04d", Integer.parseInt(minNumInString));
Зачем, если по заданию числа от 1000 до 1000?

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +            throw new IllegalArgumentException("infinity!");
Текст сообщений в исключениях должен быть более понятным, чтобы потом при анализе логов можно было гораздо быстрее определить проблему.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task7.java
> +        // а как вообще в таких случаях стоит поступать? Есть правила как разбивать код и переносить строки?
Вопросы можно писать в телегу или в виде комментов в МРе)

> а как вообще в таких случаях стоит поступать

В идеале - не писать такие длинные строки. Как вариант, их можно вынести в отдельный метод. 

> Есть правила как разбивать код и переносить строки?

Да, их множество и они определяются код-стайлом твоей команды / компании. Как вариант, можешь посмотреть в сторону гугловского код-стайла.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task7.java
> +        String inputNumAsString = Integer.toString(n, 2);
На будущее, если будет свободное время и желание, можно попробовать переписать этот метод без конвертации в строки, используя битовые операции.

2023-10-15 09:25 UTC, SHvatov commented on src/main/java/edu/hw1/Task8.java
> +                    checkCoordinates(i - 2, j - 1, chessBoard)
1. Такие длинные условия лучше не писать, а выносить их в методы, типа `if (isKnightPresent(chessBoard, i, j) && canKnightEatSomeone(chessboard, i, j))`.Так гораздо легче понять код. 
2. `checkCoordinates` не лучшее имя для белового метода. Такие методы дают ответ на задаваемый вопрос, поэтому и имеют в названии вопросительную форму - `isValid, isApplicable, isKnightPresent. etc`. `checkCoordinates` же больше похож на войдовый метод, который проверяет координаты и в случае чего кидает исключение.

2023-10-15 09:25 UTC, SHvatov commented on src/test/java/edu/hw1/Task1Test.java
> +        String s = "01:01";
1. Давай добавим тест на ту строку, о которой я писал раньше
2. Давай попробуем эти тесты заменить на [параметризованные](https://www.baeldung.com/parameterized-tests-junit-5). Это позволит избавиться от бойлерплейта при написании таких типовых тестов.

2023-10-15 09:25 UTC, SHvatov commented on src/test/java/edu/hw1/Task8Test.java
> +    static class ArrayArgumentsProvider implements ArgumentsProvider {
В комменте выше кинул статью, там про это есть.

2023-10-15 15:45 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task1.java
> +            minuts = Integer.parseInt(input.split(":")[0]);
С регуляркой пока не придумал, но на будущее учту про исключения)

2023-10-15 15:45 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task1.java
> +        if (seconds >= SECONDS) {
исправил)

2023-10-15 15:46 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task3.java
> +        int minElementFirstArray = Integer.MAX_VALUE;
Сделал через стримы)

2023-10-15 15:46 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task5.java
> +        String s = Integer.toString(Math.abs(num));
исправил)

2023-10-15 15:46 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task6.java
> +        if (Math.abs(num) == KAPREKAR_CONST) {
думал таких данных не будет) добавил проверку и тест

2023-10-15 15:48 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task6.java
> +        minNumInString = String.format("%04d", Integer.parseInt(minNumInString));
ой, я неправильны коммент написал, имелось ввиду minNumInString < 1000, нули нужны для реверса строки

2023-10-15 15:48 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task6.java
> +            throw new IllegalArgumentException("infinity!");
исправил

2023-10-15 15:50 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task7.java
> +        // а как вообще в таких случаях стоит поступать? Есть правила как разбивать код и переносить строки?
я гугловский код стайл даже в проект добавил, стоит ему доверить разбиение по Ctrl + Alt + L?

2023-10-15 15:50 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task7.java
> +        String inputNumAsString = Integer.toString(n, 2);
да, сейчас уже не успеваю...

2023-10-15 15:51 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task8.java
> +                    checkCoordinates(i - 2, j - 1, chessBoard)
отрефакторил

2023-10-15 15:54 UTC, timkotov2003 commented on src/test/java/edu/hw1/Task1Test.java
> +        String s = "01:01";
Ага, написал.
Один параметризованный тест лучше чем много мелких?
Просто для каждого теста по отдельности можно написать название для какой ситуации он, а тут получается всё в кучу.
Но в общем сделал, посмотрите пожалуйста.

2023-10-15 15:58 UTC, timkotov2003 commented on src/test/java/edu/hw1/Task8Test.java
> +    static class ArrayArgumentsProvider implements ArgumentsProvider {
Спасибо за статью!
сделал через аннотацию MethodSource (он вроде самый удобный, или стоило по другому сделать?)

2023-10-15 15:59 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task1.java
> +    public static final int SECONDS = 60;
исправил

2023-10-15 15:59 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task1.java
> +        int minuts;
исправил

2023-10-15 16:37 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +        int minuts;
`minuts ` -> `minutes` :)

2023-10-15 16:38 UTC, SHvatov commented on src/main/java/edu/hw1/Task3.java
> +        int minElementFirstArray = Integer.MAX_VALUE;
и все-таки, даже стримы можно унести в методы

2023-10-15 16:41 UTC, SHvatov commented on src/main/java/edu/hw1/Task5.java
> +        String stringFromInputNum = Integer.toString(Math.abs(num));
1. можно просто `numAsString`
2. на 19 строке можно без else, чтобы уменьшить вложенность 
3. я бы сделал приватный внутренний метод, который бы на вход принимал строку — тогда на 18 строке тебе не пришлось бы конвертить строку в число, только чтобы чуть позже снова конвертнуть это число в строку.

2023-10-15 16:41 UTC, SHvatov commented on src/main/java/edu/hw1/Task5.java
> +                sb.append(stringFromInputNum.charAt(i * 2) - '0' + stringFromInputNum.charAt(i * 2 + 1) - '0');
'0' можно вынести в константу

2023-10-15 16:42 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        if (Math.abs(num) == KAPREKAR_CONST) {
лучше исходить из того, что невалидные данные будут всегда :)

2023-10-15 16:56 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        minNumInString = String.format("%04d", Integer.parseInt(minNumInString));
и все равно программа принимает на вход не четырехзначные числа, а, засчет этой строки, интерпретирует их как четырехзначные)

2023-10-15 16:57 UTC, SHvatov commented on src/main/java/edu/hw1/Task8.java
> +    public static boolean isCoordinatesChecked(int x, int y, int[][] array) {
`isCoordinatesChecked` - координаты проверены на что?) Стоит конкретизировать.

2023-10-15 16:58 UTC, SHvatov commented on src/test/java/edu/hw1/Task8Test.java
> +    static class ArrayArgumentsProvider implements ArgumentsProvider {
Все хорошо, тут на твое усмотрение)

2023-10-15 17:00 UTC, SHvatov commented
@timkotov2003 оставил еще пару комментов, с учетом дедлайнов поставлю как есть, но буду ждать твоих правок)

2023-10-15 17:00 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task5.java
> +                sb.append(stringFromInputNum.charAt(i * 2) - '0' + stringFromInputNum.charAt(i * 2 + 1) - '0');
> '0' можно вынести в константу

Чек стайл кстати не ругался :)
ну он обычно на magic number ругается, а тут-то символ))

2023-10-15 19:21 UTC, SHvatov commented on src/test/java/edu/hw1/Task1Test.java
> +        String s = "01:01";
Завтра постараюсь посмотреть!
Параметризированные тесты в первую очередь нужны для проверки негативных / позитивных сценариев из разных классов эквивалентности. Про них можно почитать [здесь](https://habr.com/ru/articles/462553/).

2023-10-15 19:22 UTC, SHvatov commented on src/main/java/edu/hw1/Task7.java
> +        // а как вообще в таких случаях стоит поступать? Есть правила как разбивать код и переносить строки?
Да, можно так, можно в ИДЕЕ выбрать при коммите вот эти галочки
![image](https://github.com/timkotov2003/myrepository/assets/15994914/33f941f9-f2b7-4be6-a62b-fca35a9452f3)

2023-10-16 18:34 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task5.java
> +        String stringFromInputNum = Integer.toString(Math.abs(num));
переделал)

2023-10-16 18:34 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task5.java
> +                sb.append(stringFromInputNum.charAt(i * 2) - '0' + stringFromInputNum.charAt(i * 2 + 1) - '0');
сделал)

2023-10-16 18:35 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task8.java
> +    public static boolean isCoordinatesChecked(int x, int y, int[][] array) {
дописал ForEat, ну типа можно ли съесть фигуру)

2023-10-16 18:47 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task3.java
> +        int minElementFirstArray = Integer.MAX_VALUE;
Можно, но тут вроде строчка короткая + стримы за счёт декларативного подхода легко читаются, ну то есть сразу видно в коде что делаем, отдельный метод информативности не добавит, да и количество строк в даном случае не сократит

2023-10-16 18:51 UTC, timkotov2003 commented on src/main/java/edu/hw1/Task6.java
> +        minNumInString = String.format("%04d", Integer.parseInt(minNumInString));
> и все равно программа принимает на вход не четырехзначные числа, а, засчет этой строки, интерпретирует их как четырехзначные)

исправил)
Добавил тест на эту ситуацию (для 123 выкинет IllegalArgumentException)
кстати, а тесты на исключения нормально написаны? Есть какие-то комментарии по ним?

2023-10-20 18:28 UTC, SHvatov approved these changes
👍

2023-10-21 01:43 UTC, merged