feat: add homework 3
timkotov2003/myrepository pull request #4
Opened 2023-10-28 21:53 UTC by timkotov2003

2023-10-29 03:57 UTC, timkotov2003 commented on src/test/java/edu/hw3/task5/Task5Test.java
> +                "ASC",
Странно, но тут и строку нормально принимает, не только енам. А вот почему? Какая-то магия с этим Arguments.of...

2023-10-29 04:00 UTC, timkotov2003 commented on src/main/java/edu/hw3/task6/StockMarketImpl.java
> +    private final Queue<Stock> innerQueue = new PriorityQueue(Comparator.comparing(Stock::price).reversed());
Такую инициализацию лучше в конструктор выносить или в поле оставить?

2023-10-29 16:06 UTC, SHvatov commented on src/test/java/edu/hw3/task5/Task5Test.java
> +                "ASC",
Так он же не типизированный, ожидает Object. А дальше под капотом уже JUnit вполне может вызывать `valueOf` на енаме

2023-10-29 16:06 UTC, SHvatov commented on src/main/java/edu/hw3/task6/StockMarketImpl.java
> +    private final Queue<Stock> innerQueue = new PriorityQueue(Comparator.comparing(Stock::price).reversed());
Чем ближе инициализация к определению - тем лучше. Так что тут все хорошо)

2023-10-29 16:19 UTC, SHvatov requested changes
@timkotov2003 оставил пару комментариев, посмотри их, пожалуйста.

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task1/Task1.java
> +    public static String atbash(String input) {
Знаю, что в задании просто `atbash`, но я бы все-таки указал, что происходит шифрование. К примеру, `encryptViaAtbash`.

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task1/Task1.java
> +    public static final char FIRST_SMALL_LETTER = 'a';
uppercase & lowercase)

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task2/Task2.java
> +            throw new IllegalArgumentException("input string must not be null");
Еще бы проверки на то, что кол-во скобок четное и каждый кластер закрыт

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task3/Task3.java
> +        return inputList.stream().collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
🔥

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task4/Task4.java
> +    private static final Map<Integer, String> ROMAN_DIGITS = new LinkedHashMap<>() {
Вообще считается, что {{}} не лучшее решение, потому что порождает анонимные классы. Я бы просто в статическом блоке вызвал метод, в котором бы проинициализировал мапу.

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task5/Contact.java
> +    public int compareTo(Contact o) {
Не будет такого, что сравниваются два контакта - первый по фамилии, второй по имени?

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task5/Task5.java
> +    private static Contact getContactFromString(String str) {
`get` -> `parse`, для единообразия

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task7/TreeMapComparator.java
> +        if (o1 == null || o2 == null) {
Получается, что `"test" == null` в этой мапе. Посмотри на `NullComparator` в `Comparator`.

2023-10-29 16:19 UTC, SHvatov commented on src/main/java/edu/hw3/task8/BackwardIterator.java
> +    public BackwardIterator(List<E> list) {
В задании

> который принимает **коллекцию**

2023-10-29 23:56 UTC, timkotov2003 commented on src/main/java/edu/hw3/task4/Task4.java
> +    private static final Map<Integer, String> ROMAN_DIGITS = new LinkedHashMap<>() {
Переделал. А чем плох анонимный класс на основе мапы, он же от неё наследуется, по сути та же мапа, только называется по другому и компилируется во внутренний класс :)

2023-10-29 23:59 UTC, timkotov2003 commented on src/main/java/edu/hw3/task5/Contact.java
> +    public int compareTo(Contact o) {
Так будет если у второго отсутствует фамилия, но вроде по заданию так и надо в этом случае поступать

2023-10-30 00:06 UTC, timkotov2003 commented on src/main/java/edu/hw3/task5/Contact.java
> +    public int compareTo(Contact o) {
Сейчас перечитал "если фамилия отсутствует, то нужно использовать имя", я это понял так что за место фамилии у этого человека нужно использовать имя как фамилию (при сортировке)

2023-10-30 00:26 UTC, timkotov2003 commented on src/main/java/edu/hw3/task7/TreeMapComparator.java
> +        if (o1 == null || o2 == null) {
А, то есть мы этим контракт нарушаем, я правильно понимаю? Типа "a" ==  null && "b" == null   =>  получается "a" == "b", так?)
я почему-то про строгий контракт с equals и hashcode только запомнил из лекции)) и думал мы можем любой компаратор с любой логикой писать))

2023-10-30 00:34 UTC, timkotov2003 commented on src/main/java/edu/hw3/task7/TreeMapComparator.java
> +        if (o1 == null || o2 == null) {
![image](https://github.com/timkotov2003/myrepository/assets/146794328/82344943-b1a2-4ae3-85dc-31d7b72e754c)

Ну кстати, в лекции в контракте не указано что делать с null :)

2023-10-30 00:37 UTC, timkotov2003 commented on src/main/java/edu/hw3/task7/TreeMapComparator.java
> +        if (o1 == null || o2 == null) {
Переписал логику как в NullComparator, кстати, они там зачем-то пишут последний else хотя можно и без него

![image](https://github.com/timkotov2003/myrepository/assets/146794328/2252df0e-9d3c-4944-a4ed-625d1a75fad6)

2023-11-01 19:48 UTC, SHvatov commented on src/main/java/edu/hw3/task4/Task4.java
> +    private static final Map<Integer, String> ROMAN_DIGITS = new LinkedHashMap<>() {
https://www.baeldung.com/java-double-brace-initialization - вот тут советую почитать, почему это антипаттерн

2023-11-01 19:48 UTC, SHvatov commented on src/main/java/edu/hw3/task5/Contact.java
> +    public int compareTo(Contact o) {
ок, согласен, давай оставим так

2023-11-01 19:51 UTC, SHvatov commented on src/main/java/edu/hw3/task7/TreeMapComparator.java
> +        if (o1 == null || o2 == null) {
> А, то есть мы этим контракт нарушаем, я правильно понимаю? Типа "a" == null && "b" == null => получается "a" == "b", так?) я почему-то про строгий контракт с equals и hashcode только запомнил из лекции)) и думал мы можем любой компаратор с любой логикой писать))

Чисто технически логика может быть любой, только вот если логика не соответствует контракту, могут быть проблемсы) Ты прав, получается, что все объекты, исходя из данной логики, равны, что неверно)

> Ну кстати, в лекции в контракте не указано что делать с null :)

Это допущение ради упрощения) null'ы трактуются по-разному в зависимости от задачи — можешь глянуть на `Comparator.nullsLast/nullasFirst`.

2023-11-01 19:51 UTC, SHvatov approved these changes
@timkotov2003 🔥, можно мержить

2023-11-02 00:30 UTC, merged