feat: add project 2
timkotov2003/myrepository pull request #6
Opened 2023-11-05 19:58 UTC by timkotov2003

2023-11-29 16:14 UTC, Keindel requested changes
В целом хорошо и есть что улучшить.)

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +    public Maze generate(int height, int width) {
длинный метод на 50 строк, было бы здорово сделать его покороче

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +                makeWall(i, j, grid);
Не глядя код метода можно ожидать, что он работает так же как buildWall.
Я бы предложил переименовать более явно. Например, assignWallToCell.
На мой взгляд, `grid[row][col] = Cell.WALL` даже понятнее, чем метод с названием **make**Wall

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +    private void makePath(int row, int col, Cell[][] grid) {
стоит ли 1 строка того, чтобы выделять в отдельный метод?
path используется как путь в лабиринте, решение. Лучше называть makePassage.

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +        List<Direction> directions = new ArrayList<>(List.of(Direction.values()));
нужно ли на каждый вызов метода в цикле делать новый список направлений?

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +            directions.remove(dirIndex);
кажется до этой строки невозможно дойти

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +        while (!directions.isEmpty()) {
Не понимаю зачем цикл и в каждом кейсе directions.clear().

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +                case DOWN -> {
У каждого кейса подобный код, я бы предложил унифицировать.
Для направлений распространено использование массива вида `int[][] directions = {{0, 2}, {0, -2}, {2, 0}, {-2, 0}};` - можно попробовать с этим или иначе.

2023-11-29 16:14 UTC, Keindel commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +    private void addCellsToCheck(
в этом методе тоже можно попробовать унифицировать с помощью массива вида `int[][] directions = {{0, 2}, {0, -2}, {2, 0}, {-2, 0}};`

2023-11-29 16:14 UTC, Keindel commented on pom.xml
> +            <artifactId>lombok</artifactId>
👍

2023-11-29 16:14 UTC, Keindel commented on pom.xml
> +            <artifactId>mockito-core</artifactId>
не заметил, где-то используется?

2023-11-30 12:38 UTC, timkotov2003 commented on pom.xml
> +            <artifactId>mockito-core</artifactId>
Нет) это мы просто на лекции проходили, поэтому решил добавить, а так пока в тестах ничего мокать не приходилось

Сейчас большая загруженность в универе по учёбе, с учётом того что  комментарии в основном не критичные (скорее на уровне рефакторинга), надеюсь можно не исправлять? Очень не хочется лезть в код месячной давности и тратить время, а 7/10 баллов меня устроит

2023-11-30 12:55 UTC, Keindel commented on pom.xml
> +            <artifactId>mockito-core</artifactId>
Понимаю. Можем оставить 7/10. Или 6 из 8 комментов отработаешь - поставлю 10. На твой выбор каких =)

2023-11-30 12:59 UTC, timkotov2003 commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +            directions.remove(dirIndex);
Нет, почему, можно. Если case сработал, а if в нём нет. Тогда доходим до этой строки и новая итерация со свитчем

2023-11-30 13:04 UTC, timkotov2003 commented on src/main/java/edu/project2/generator/impl/PrimGenerator.java
> +        while (!directions.isEmpty()) {
Перебираем до тех пор пока для случайно выбранного направления не выполнится соответствующее условие, вроде так, хотя я уже и сам плохо помню что там

2023-11-30 13:11 UTC, timkotov2003 commented on pom.xml
> +            <artifactId>mockito-core</artifactId>
Времени всё равно нет :) а ещё новые домашки делать... Согласен на 7/10, на портале edu нажал кнопку что доработал (по факту нет, но просто чтобы вы засчитали работу с 7 баллами)

2023-11-30 13:14 UTC, timkotov2003 commented on pom.xml
> +            <artifactId>mockito-core</artifactId>
Не знаю кстати, надо ли было на портале что-то нажимать, может можно было и без этого

2023-11-30 13:25 UTC, Keindel approved these changes

2023-12-03 15:06 UTC, merged